language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.4

script:
 - cd hw-ruby-intro
 - bundle install
 - bundle exec rspec
 - cd ../hw-ruby-more
 - bundle install
 - bundle exec rspec